server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/message?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  type-aliases-package: com.message.demo.bean
